---
- name: Build simple crew modification for multiple regions
  hosts: all
  vars:
   build_id: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
   game_version: 0.7.2.1
   region: "{{ lookup('env','REGION') }}"
  roles:
    - role: prepare
    - role: dependency
      dependency_list:
        - { git_repo: 'https://github.com/Monstrofil/game_client_files.git', destination: '@game-files' }
    - role: require
      files:
        - { src: '@game-files/gui/unbound/dock.xml',
            destination: 'gui/unbound/' }
        - { src: '@game-files/gui/flash/USSExpressionsLoader.xml',
            destination: 'gui/flash/' }
    - role: patch
      patches:
        - { patch: 'src/{{ region }}/dock.xml.patch', original: 'gui/unbound/dock.xml' }
    - role: usscompile
      files:
        - { src: 'gui/unbound/dock.xml', name: 'simple_crew' }

  post_tasks:
    - name: create res_mods structure
      file: path=tmp/dest/res_mods/{{ game_version }} state=directory

    - name: copy build directory into res_mods
      command: cp -r tmp/build/. tmp/dest/res_mods/{{ game_version }}/

    - name: Ansible zip directory example
      archive:
        path:
          - tmp/dest/
        dest: "{{ build_id }}.zip"
        format: zip

    - name: remove build directory
      file: path=tmp/build state=absent

    - name: remove dest directory
      file: path=tmp/dest state=absent