---
- name: Build simple crew modification for multiple regions
  hosts: all
  vars:
   name: simple_crew
   build_id: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
   game_version: 0.7.2.1
   region: "{{ lookup('env','REGION') }}"
  roles:
    - role: prepare
    - role: dependency
      dependency_list:
        - { git_repo: 'https://github.com/Monstrofil/game_client_files.git', destination: '@game-files' }
    - role: require
      files:
        - { src: '@game-files/gui/unbound/dock.xml',
            destination: 'gui/unbound/' }
        - { src: '@game-files/gui/flash/USSExpressionsLoader.xml',
            destination: 'gui/flash/' }
    - role: patch
      patches:
        - { patch: 'src/{{ region }}/dock.xml.patch', original: 'gui/unbound/dock.xml' }
  tasks:
    - name: add required string into USSExpressionsLoader.xml
      xml:
        path: tmp/build/gui/flash/USSExpressionsLoader.xml
        xpath: /data/expressions_files
        pretty_print: yes
        add_children:
          - file:
              path: ../unbound/flash/dock.swf

  post_tasks:
    - name: create res_mods structure
      file: path=tmp/dest/res_mods/{{ game_version }} state=directory

    - name: copy build directory into res_mods
      command: cp -r tmp/build/. tmp/dest/res_mods/{{ game_version }}/

    - name: Ansible zip directory example
      archive:
        path:
          - tmp/dest/
        dest: "{{name}}_{{ build_id }}.zip"
        format: zip

    - name: remove build directory
      file: path=tmp state=absent