- name: Initialize build directory
  file:
    path: "tmp/build/"
    state: directory
    mode: 0775
    recurse: yes

- name: check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  register: pip_is_installed
  changed_when: false

- block:
    - name: download get-pip.py
      get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp

    - name: install pip
      command: "python /tmp/get-pip.py"

    - name: delete get-pip.py
      file: state=absent path=/tmp/get-pip.py

  when: pip_is_installed.rc != 0

- name: install pip packages
  pip:
    name: lxml

- name: check to see if flexsdk is already installed
  stat: path=tmp/flexsdk
  register: flexsdk_is_installed
  ignore_errors: true
  changed_when: false

- block:
  - name: download flexSDK to remote
    get_url:
      url: http://download.macromedia.com/pub/flex/sdk/flex_sdk_4.6.zip
      dest: tmp

  - name: Unzip flexSDK to remote
    command: unzip -n tmp/flex_sdk_4.6.zip -d tmp/flexsdk

  when: flexsdk_is_installed.stat.exists == False

- name: install java
  apt:
    name: default-jre
    state: present